(in-package :mcclim-desktop-user)

(setf *application* (find-application "beirc"))

(setf (application-entry-fn *application*)
      #'(lambda (app &rest args)
	  (declare (ignore app args))
	  (beirc:beirc :new-process nil)))

(setf (application-config-fn *application*)
      #'(lambda (app)
	  (setf beirc:*beirc-user-init-file* (application-config-file app))
	  (setf beirc:*default-fill-column* 110)
	  ;;(setf beirc:*default-sound-player* nil)
	  (setf beirc:*default-nick* (format nil "gas2serra"))
	  (setf beirc::*default-realname* (format nil "Alessandro"))
	  (setf beirc:*default-web-browser "/usr/bin/firefox")
	  (setf beirc::*auto-connect-list* '("irc.freenode.net"))
	  (setf beirc::*auto-identify-list* '("irc.freenode.net"))
	  (setf beirc::*nickserv-password-alist* '(("irc.freenode.net" . "password")))
	  (setf beirc:*auto-join-alist* '(("irc.freeenode.net" . ("#maxima" "#lisp" "#clnoobs" "#sbcl" "#lispgames" "#scheme" "#emacs" "#algorithms" "##cs" "##programming" "##math" "##asm" "##linux" "##kernel" "##slackware" "#freenode"))))
	  nil))

(defmethod irc::nickname ((u (eql nil)))
  nil)
